import {
  Activity,
  BarChart3,
  Bell,
  Boxes,
  CreditCard,
  DatabaseBackup,
  Gauge,
  Globe2,
  HeartPulse,
  KeyRound,
  Languages,
  LifeBuoy,
  Package,
  ReceiptText,
  Settings,
  Shield,
  ShieldAlert,
  TicketPercent,
  Truck,
  Users
} from "lucide-react";

export const navItems = [
  { href: "/", label: "Dashboard", icon: Gauge },
  { href: "/products", label: "Products", icon: Package },
  { href: "/categories", label: "Categories", icon: Boxes },
  { href: "/orders", label: "Orders", icon: ReceiptText },
  { href: "/customers", label: "Customers", icon: Users },
  { href: "/analytics", label: "Analytics", icon: BarChart3 },
  { href: "/payments", label: "Payments", icon: CreditCard },
  { href: "/delivery", label: "Delivery", icon: Truck },
  { href: "/localization", label: "Localization", icon: Languages },
  { href: "/notifications", label: "Notifications", icon: Bell },
  { href: "/support", label: "Support", icon: LifeBuoy },
  { href: "/audit", label: "Audit Logs", icon: Activity },
  { href: "/security", label: "Security", icon: ShieldAlert },
  { href: "/api-settings", label: "API Settings", icon: KeyRound },
  { href: "/access", label: "Access", icon: Shield },
  { href: "/backups", label: "Backups", icon: DatabaseBackup },
  { href: "/health", label: "Health", icon: HeartPulse },
  { href: "/referrals", label: "Referrals", icon: TicketPercent },
  { href: "/settings", label: "Settings", icon: Settings },
  { href: "/website", label: "Website", icon: Globe2 }
] as const;
