from __future__ import annotations

LANG = "lang"
HOME = "home"
STORE = "store"
FEATURED = "featured"
CATEGORIES = "cats"
CATEGORY = "cat"
SEARCH = "search"
FILTERS = "filters"
PRODUCT = "prod"
BUY = "buy"
CHECKOUT_CONFIRM = "co"
PAYMENT_METHOD = "pay"
SUBMIT_PAYMENT = "subpay"
ORDERS = "orders"
WALLET = "wallet"
REFERRAL = "ref"
SUPPORT = "support"
SUPPORT_NEW = "supnew"
SUPPORT_LIST = "suplist"
PROFILE = "profile"
API_KEY = "apikey"
REGENERATE_API_KEY = "regenkey"

